version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    image: https://hub.docker.com/u/rajusinghstm/flaskp-frontend:latest
    container_name: flaskp_frontend
    ports:
      - "3000:3000"
    environment:
      - FLASK_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - flaskp-net

  backend:
    build:
      context: ./backend
    image: https://hub.docker.com/u/rajusinghstm/flaskp-backend:latest
    container_name: flaskp_backend
    ports:
      - "5000:5000"
    networks:
      - flaskp-net

networks:
  flaskp-net:
    driver: bridge
